name: Build and Push Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker Image (release)
    env:
      DOCKERHUB_USERNAME: pdreker
      IMAGE: fritz_datacollector
    steps:
      - uses: actions/checkout@v4
      - name: generate docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - name: generate requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
