name: check PR labels

on:
  pull_request:
    branches:
      - main
    types: ["opened", "synchronize", "labeled", "unlabeled"]

jobs:
  check-label:
    runs-on: ubuntu-latest
    outputs:
      pr_tags_present: ${{ steps.pr_label_check.outputs.label_check }}
    steps:
      - uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "patch, minor, major"
      - id: pr_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: patch, minor, major
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true
  update-versions:
    needs: check-label
    if: ${{ needs.check-label.outputs.pr_tags_present == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Compute next SemVer
        id: update_semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: pr_branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.vars.outputs.branch }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.1
      - name: Update version in pyproject.toml
        run: |
          V_VERSION=${{ steps.update_semver.outputs.tag }}
          poetry version "${V_VERSION//v/}"
      - name: Update internal VERSION string
        run: echo VERSION = \"${{ steps.update_semver.outputs.tag }}\" > fritz_datacollector/_version.py
      - name: Commit version files back to repo
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add pyproject.toml fritz_datacollector/_version.py
          git commit -m "Update version files to ${{ steps.update_semver.outputs.tag }}"
      - name: Push version updates back to PR
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ steps.vars.outputs.branch }}
