name: check PR labels

on:
  pull_request:
    branches:
      - master
    types: ["opened", "synchronize", "labeled", "unlabeled"]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "patch, minor, major"
