name: Tag release

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      - fritz_datacollector/_version.py

jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag release
    steps:
      - name: Push SemVer release tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_PUSH_TOKEN }}
