name: Update versions and release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tag-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    name: Tag release
    needs: update-versions
    steps:
      - uses: actions/checkout@v3
      - name: Push SemVer release tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_PUSH_TOKEN }}
